#!/bin/bash
set -ue

# Cross-compile passed .c file to .wasm and .cwasm files
#
# Usage:
#   export LIND_CC="/path/to/clang --sysroot=/absolute/path/to/sysroot"
#   export LIND_WASMOPT="/path/to/wasm-opt"
#   export LIND_WASMTIME="/path/to/wasmtime"
#
#   ./lind_compile /path/to/program.c
#
# TODO: Default to clang, wasm-opt and wasmtime on PATH, if env vars are not set.
# Use convention for sysroot path, e.g. relative to clang binary?

# Require exactly one argument, with .c extension
if [[ "$#" -ne 1 || "${1: -2}" != ".c" ]]; then
    echo "usage: $0 </path/to/*.c file>"
    exit 1
fi

path_c="$1"
path_wasm="${1%.c}.wasm"
path_cwasm="${1%.c}.cwasm"

$LIND_CC -pthread --target=wasm32-unknown-wasi \
    -Wl,--import-memory,--export-memory,--max-memory=67108864,--export="__stack_pointer",--export=__stack_low \
    "$path_c" -g -O0 -o "$path_wasm"
$LIND_WASMOPT --epoch-injection --asyncify -O2 --debuginfo "$path_wasm" -o "$path_wasm"
$LIND_WASMTIME compile "$path_wasm" -o "$path_cwasm"
